version: "3.8"
services:

  heads_up_redis:
      image: redis
      container_name: heads_up_redis

  heads_up_backend:
    build: 
      context: ./backend
    volumes:
      - .:/backend
    ports:
      - 8000:8000 
    image: heads_up_backend:backend
    container_name: heads_up
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - heads_up_redis

  heads_up_frontend:
    build:
      context: ./frontend/heads_up
    volumes:
      - react_build:/react/build

  heads_up_nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
    depends_on:
      - heads_up_backend
      - heads_up_frontend

volumes:
  react_build: