# Generated by Django 4.1.3 on 2022-11-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_backend', '0003_gameroom_is_ended_gameroom_is_started_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuessCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
    ]
